///@ 参数配置
ATTRIBUTE_PARAM_DEFINE( MingZhongLv,      1,   "命中率")
ATTRIBUTE_PARAM_DEFINE( BaoJiLv,          2,   "暴击率")
ATTRIBUTE_PARAM_DEFINE( BPSubMoveSpeed,   3,   "负重降低移动速度")
ATTRIBUTE_PARAM_DEFINE( Hurt,             4,   "伤害")
ATTRIBUTE_PARAM_DEFINE( Water,            5,   "水")
ATTRIBUTE_PARAM_DEFINE( DistanceHurt,     6,   "根据距离算伤害公式")
ATTRIBUTE_PARAM_DEFINE( BlastDistance,    7,   "计算击退距离")
ATTRIBUTE_PARAM_DEFINE( BodySize,         8,   "角色大小")
ATTRIBUTE_PARAM_DEFINE( AttackSkillRevise,9,   "技能攻击的修正")
ATTRIBUTE_PARAM_DEFINE( HelpCarryPrincessWeight,10,"协助搬运公主时，公主的重量计算公式")
ATTRIBUTE_PARAM_DEFINE( MatchElo,11,"比赛结算elo值公式")
ATTRIBUTE_PARAM_DEFINE( MatchPredictTime,12,"预计加入比赛时间")
ATTRIBUTE_PARAM_DEFINE( MaxFlyEffectSkillVerifyAngle,13,"子弹类技能角度验证最大值")
