// 装备属性声明,需要严格遵守规则,不要加任何其他代码

/// @brief 装备基本属性
#ifdef EQUIP_BASE_ATTRIBUTE
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddAttackValue,         addattackvalue,         0,    "增加血量值" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddAttackPercent,       addattackpercent,       0,    "增加血量万分比" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddDefenceValue,        adddefencevalue,        0,    "增加防御值" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddDefencePercent,      adddefencepercent,      0,    "增加防御万分比" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddMagicAttackValue,    addmagicattackvalue,    0,    "增加魔法攻击值" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddMagicAttackPercent,  addmagicattackpercent,  0,    "增加魔法攻击万分比" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddMPValue,             addmpvalue,             0,    "增加魔法值" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddMPPercent,           addmppercent,           0,    "增加魔法值万分比" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddHPValue,             addhpvalue,             0,    "增加生命值" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddHPPercent,           addhppercent,           0,    "增加生命值万分比" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddMagicDefenceValue,   addmagicdefencevalue,   0,    "增加魔法防御" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddMagicDefencePercent, addmagicdefencepercent, 0,    "增加魔法防御万分比" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  SubRemoteHurt,          subremotehurt,      0,    "降低远程伤害" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  SubCloseHurt,           subclosehurt,       0,    "降低近战伤害" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  SubNormalHurt,          subnormalhurt,      0,    "降低物理伤害" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  SubMagicHurt,           submagichurt,       0,    "降低魔法伤害" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  HitValue,               hitvalue,           0,    "命中" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AppendHit,              appendhit,          0,    "额外命中" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AvoidValue,             avoidvalue,         0,    "闪避" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AppendAvoid,            appendavoid,        0,    "额外闪避" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  Crit,                   crit,               0,    "暴击" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AppendCrit,             appendcrit,         0,    "额外暴击" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  CritDefence,            critdefence,        0,    "暴防" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AppendCritDefence,      appendcritdefence,  0,    "额外暴防" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  CritValue,              critvalue,          0,    "暴伤" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  PureDamage,             puredamage,         0,    "纯粹伤害" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AbsorbBlood,            absorbblood,        0,    "吸血" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  Rebound,                rebound,            0,    "固定反弹" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AbsorbRebound,          reboundpercent,     0,    "反弹百分比" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  KillAddHP,              killaddhp,          0,    "击杀回血" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  HitAddHP,               hitaddhp,           0,    "击中回血" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  BeAttackAddHP,          beattackaddhp,      0,    "被击回血" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  KillAddMP,              killaddmp,          0,    "击杀回蓝" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  HitAddMP,               hitaddmp,           0,    "击中回蓝" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  BeAttackAddMP,          beattackaddmp,      0,    "被击回蓝" )
    EQUIP_BASE_ATTRIBUTE(DWORD,  AddMoveSpeed,           addmovespeed,       0,    "增加移动速度" )
#endif
