//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Platform.proto
namespace protocol.platform
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QQGameLoginData")]
  public partial class QQGameLoginData : global::ProtoBuf.IExtensible
  {
    public QQGameLoginData() {}
    
    private string _openID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"openID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string openID
    {
      get { return _openID; }
      set { _openID = value; }
    }
    private string _openKey = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"openKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string openKey
    {
      get { return _openKey; }
      set { _openKey = value; }
    }
    private string _pfKey = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pfKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pfKey
    {
      get { return _pfKey; }
      set { _pfKey = value; }
    }
    private bool _isBlueVip = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isBlueVip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBlueVip
    {
      get { return _isBlueVip; }
      set { _isBlueVip = value; }
    }
    private bool _isBlueYearVip = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isBlueYearVip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBlueYearVip
    {
      get { return _isBlueYearVip; }
      set { _isBlueYearVip = value; }
    }
    private uint _blueVipLevel = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"blueVipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint blueVipLevel
    {
      get { return _blueVipLevel; }
      set { _blueVipLevel = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _gender = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private bool _isHighBlueVip = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isHighBlueVip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isHighBlueVip
    {
      get { return _isHighBlueVip; }
      set { _isHighBlueVip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginSessionData")]
  public partial class LoginSessionData : global::ProtoBuf.IExtensible
  {
    public LoginSessionData() {}
    
    private uint _clientID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint clientID
    {
      get { return _clientID; }
      set { _clientID = value; }
    }
    private string _accountName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accountName
    {
      get { return _accountName; }
      set { _accountName = value; }
    }
    private bool _isAdult;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isAdult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isAdult
    {
      get { return _isAdult; }
      set { _isAdult = value; }
    }
    private uint _channelID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"channelID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint channelID
    {
      get { return _channelID; }
      set { _channelID = value; }
    }
    private uint _netType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"netType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint netType
    {
      get { return _netType; }
      set { _netType = value; }
    }
    private uint _platformType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"platformType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint platformType
    {
      get { return _platformType; }
      set { _platformType = value; }
    }
    private protocol.platform.QQGameLoginData _qqGameLoginData = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"qqGameLoginData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.platform.QQGameLoginData qqGameLoginData
    {
      get { return _qqGameLoginData; }
      set { _qqGameLoginData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginFailData")]
  public partial class LoginFailData : global::ProtoBuf.IExtensible
  {
    public LoginFailData() {}
    
    private uint _clientID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint clientID
    {
      get { return _clientID; }
      set { _clientID = value; }
    }
    private uint _errorCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginSuccData")]
  public partial class LoginSuccData : global::ProtoBuf.IExtensible
  {
    public LoginSuccData() {}
    
    private uint _clientID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint clientID
    {
      get { return _clientID; }
      set { _clientID = value; }
    }
    private string _accountName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accountName
    {
      get { return _accountName; }
      set { _accountName = value; }
    }
    private string _gatewayIP;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gatewayIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gatewayIP
    {
      get { return _gatewayIP; }
      set { _gatewayIP = value; }
    }
    private uint _gatewayPort;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gatewayPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gatewayPort
    {
      get { return _gatewayPort; }
      set { _gatewayPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneState")]
  public partial class ZoneState : global::ProtoBuf.IExtensible
  {
    public ZoneState() {}
    
    private uint _onlineNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"onlineNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint onlineNum
    {
      get { return _onlineNum; }
      set { _onlineNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}