# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/Proto/RoomData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol/Proto/RoomData.proto',
  package='protocol.room',
  serialized_pb='\n\x1dprotocol/Proto/RoomData.proto\x12\rprotocol.room')





# @@protoc_insertion_point(module_scope)
