# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/Proto/SequenceData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol/Proto/SequenceData.proto',
  package='protocol.serialize',
  serialized_pb='\n!protocol/Proto/SequenceData.proto\x12\x12protocol.serialize\"\x86\x01\n\x10UserSequenceData\x12@\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x32.protocol.serialize.UserSequenceData.SequenceValue\x1a\x30\n\rSequenceValue\x12\x0e\n\x06\x63harID\x18\x01 \x02(\r\x12\x0f\n\x07seqData\x18\x02 \x01(\r')




_USERSEQUENCEDATA_SEQUENCEVALUE = _descriptor.Descriptor(
  name='SequenceValue',
  full_name='protocol.serialize.UserSequenceData.SequenceValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='charID', full_name='protocol.serialize.UserSequenceData.SequenceValue.charID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqData', full_name='protocol.serialize.UserSequenceData.SequenceValue.seqData', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=192,
)

_USERSEQUENCEDATA = _descriptor.Descriptor(
  name='UserSequenceData',
  full_name='protocol.serialize.UserSequenceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='protocol.serialize.UserSequenceData.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_USERSEQUENCEDATA_SEQUENCEVALUE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=192,
)

_USERSEQUENCEDATA_SEQUENCEVALUE.containing_type = _USERSEQUENCEDATA;
_USERSEQUENCEDATA.fields_by_name['data'].message_type = _USERSEQUENCEDATA_SEQUENCEVALUE
DESCRIPTOR.message_types_by_name['UserSequenceData'] = _USERSEQUENCEDATA

class UserSequenceData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class SequenceValue(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _USERSEQUENCEDATA_SEQUENCEVALUE

    # @@protoc_insertion_point(class_scope:protocol.serialize.UserSequenceData.SequenceValue)
  DESCRIPTOR = _USERSEQUENCEDATA

  # @@protoc_insertion_point(class_scope:protocol.serialize.UserSequenceData)


# @@protoc_insertion_point(module_scope)
