#ifndef _N_SYS_H_
#define _N_SYS_H_

#include <string>
#include <deque>
#include <ext/numeric>
#include <pwd.h>
#include <sched.h>
#include <google/heap-checker.h>
#include <google/protobuf/message.h>
#include <google/profiler.h>
#include <google/tcmalloc.h>
#include <unistd.h>
#include <signal.h>
#include <stdio.h>
#include <cstdlib>
#include <sys/types.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <vector>
#include <bitset>
#include <ext/pool_allocator.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <curl/curl.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <netinet/tcp.h>
#include <dirent.h>
#include <execinfo.h>
#include <cxxabi.h>
#include <map>
#include <sys/time.h>
#include <argp.h>
#include <assert.h>
#include <deque>
#include <ext/numeric>
#include <ext/mt_allocator.h>
#include <ext/hash_map>
#include <ext/hash_set>
#include <tr1/memory>
#include <sys/epoll.h>
#include <sys/poll.h>
#include <fstream>
#include <stack>
#include <queue>
#include <sys/timeb.h>
#include <ext/mt_allocator.h>
#include <iconv.h>
#include <openssl/des.h>
#include <strings.h>
#include <set>
#include <malloc.h>
#include <cstring>
#include <cctype>
#include <cstdio>
#include <cerrno>
#include <ctime>
#include <algorithm>
#include <regex.h>
#include <iostream>
#include <list>
#include <sigc++/sigc++.h>
#include <arpa/inet.h>
#include <limits.h>
#include <errno.h>
#include <time.h>
#include <sstream>
#include <tinyxml.h>
#include <zlib.h>
#include <string.h>
#include <cassert>
#include <ostream>
#include <mysql++/mysql++.h>
#include <math.h>
#include <cmath>
#include <sys/un.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <openssl/md5.h>
#include <openssl/evp.h>
#include <rapidjson/rapidjson.h>
#include <rapidjson/stringbuffer.h>
#include <rapidjson/writer.h>
#include <syslog.h>
#include <float.h>
#include <lua.hpp>
#include <tolua++.h>

#include "base/nType.h"

#endif
